-- MySQL Script generated by MySQL Workbench
-- Mon Oct 14 10:01:05 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema movieratingsdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema movieratingsdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `movieratingsdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `movieratingsdb` ;

-- -----------------------------------------------------
-- Table `movieratingsdb`.`rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movieratingsdb`.`rating` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Code` LONGTEXT NULL DEFAULT NULL,
  `Description` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `movieratingsdb`.`movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movieratingsdb`.`movie` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Title` LONGTEXT NOT NULL,
  `ReleaseDate` DATETIME NULL DEFAULT NULL,
  `RatingId` INT(11) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_RatingId` (`RatingId` ASC) VISIBLE,
  CONSTRAINT `FK_Movie_Rating_RatingId`
    FOREIGN KEY (`RatingId`)
    REFERENCES `movieratingsdb`.`rating` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
